framework:
  mailer:
    dsn: "%env(MAILER_DSN)%"
    headers:
      from: Alstef Canada <reporting@alstefgroup.com>
      #from: Alstef_reporting <reporting@alstefgroup.com> Boss <djamenvanick@gmail.com>
