#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# index:
#   path: /
#   controller: App\Controller\ConnectionController::index

index:
  path: /
  controller: App\Controller\EmailController::index
